[project]
name = "ml-ops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Usman Asif", email = "usman.hussain@10pearls.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "joblib>=1.5.3",
    "mlflow>=3.15.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.9.0",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
