[project]
name = "ml-ops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Usman Asif", email = "usman.hussain@10pearls.com" }
]
requires-python = ">=3.14"
dependencies = [
    "joblib>=1.5.3",
    "jupyter>=1.1.1",
    "scikit-learn>=1.9.0",
]
