apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-ops-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/usmanasif-10P/ml-ops
    targetRevision: main
    path: k8s/mlapp

  destination:
    server: https://kubernetes.default.svc
    namespace: ml-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true