apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-ops-api
  namespace: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-ops-api
  template:
    metadata:
      labels:
        app: ml-ops-api
    spec:
      containers:
        - name: ml-ops-api
          image: usmanasif10p/ml-ops:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.mlflow:5000"